version: "3"

services:
  app:
    container_name: partners
    build: ./docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/var/app
    ports:
      - 3000:3000
    environment:
      - VOLUME_APP=$PWD
    networks:
      partners-network:
        ipv4_address: 10.0.2.10

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      partners-network:
        ipv4_address: 10.0.2.11

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      partners-network:
        ipv4_address: 10.0.2.12

networks:
  partners-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.10/24